[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
swap_program = "4yCxmVu65qfVi4wreCW58yudn8Mz41LJ8yTMUXeoPUTB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
create-tokens = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/create-tokens.test.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/main.test.ts"
upload-json = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/upload-json.test.ts"
